### ISSUE TITLE
sharedLibs not working properly when adding the list of shared libs

### ISSUE THREAD

**Issue by kropladev** [orctom/was-maven-plugin#13]
Tested on IBM WebSphere Application Server, 7.0.0.27.
Everything is working perfectly exact the adding the shared libraries more than one on list. In such case only the last shared lib from the list is added.

**Comment by orctom** [comment]
Can you past your configure section?

**Comment by kropladev** [comment]
It is something like that below. Only the last is set to the project. Also
when I try to add those shared libs separated by space - the value is set
but with space so in ibm/console I still can add all of those libs
separately.

<configuration>
<wasHome>${env.WAS_HOME}</wasHome>
<applicationName>${project.build.finalName}</applicationName>
<host>localhost</host>
<server>server1</server>
<node>SOFT-003Node01</node>
<virtualHost>default_host</virtualHost>
<contextRoot>/${project.build.finalName}</contextRoot>
<verbose>true</verbose>
<sharedLibs>PR_LIBS,PR_MISSING_LIBS</sharedLibs>
<webModuleParentLast>true</webModuleParentLast>
</configuration>

2016-02-15 12:44 GMT+01:00 ORCTOM notifications@github.com:

**Comment by orctom** [comment]
Please try version:`1.1.3` in 2 hours.

**Comment by kropladev** [comment]
I've got exception on version 1.1.3:
Traceback (most recent call last):
  File "<string>", line 134, in installApplication
com.ibm.ws.scripting.ScriptingException: com.ibm.ws.scripting.ScriptingException: java.lang.ClassCastException: java.lang.ClassCastException: java.lang.String incompatible with java.util.List

**Comment by orctom** [comment]
Can you paste the `options` line in the logs, there're log files locates in `target/was-maven-plugin/py/*.log` line:16

**Comment by orctom** [comment]
I missed a pair of brackets.
Version `1.1.3.1` should do the magic, which is already available.

**Comment by kropladev** [comment]
Now it is working. Thanks
