### ISSUE TITLE
Issues with deploying to Web Server in a Single target server

### ISSUE THREAD

**Issue by GPCruisr** [orctom/was-maven-plugin#14]
Use Case is to deploy an application to a stand alone WAS Server and map it to IHS.

In the pom.xml file in the config section, we have 'server' and 'webservers' but the application is only being deployed to 'server' but not to the 'webservers'.   

We are using the 1.1.2 version of the plugin and Version 8.5.5. of WAS.

**Comment by orctom** [comment]
Can you paste your `webservers` value here?

**Comment by orctom** [comment]
I assume this is not an issue.
