### ISSUE TITLE
Issues with deploying to Web Server in a Single target server

### ISSUE THREAD

**Issue by GPCruisr** [orctom/was-maven-plugin#16]
This is a followup to my previous.   Apologies, but I didn't come back and check for status and it got closed. 

Use Case is to deploy an application to a stand alone WAS Server and map it to IHS.

In the pom.xml file in the config section, we have 'server' and 'webservers' but the application is only being deployed to 'server' but not to the 'webservers'.

We are using the 1.1.2 version of the plugin and Version 8.5.5. of WAS.

My values for the the command used by Maven are pulled from the Maven settings.xml and  are as follows:
[settings for maven.txt](https://github.com/orctom/was-maven-plugin/files/470523/settings.for.maven.txt)

I have the pom.xml plugin configured as follows:

[maven setup for was plugin.txt](https://github.com/orctom/was-maven-plugin/files/470520/maven.setup.for.was.plugin.txt)

When I look in my log I see that it puts together this option string:
options:  ['-distributeApp', '-appname', 'RetrieveProviderReport', '-MapModulesToServers', [['._', '._', 'WebSphere:server=ABCD29AS13']], '-MapWebModToVH', [['._', '._', 'default_host']]]

I would expect to see my value of 'webservers' in that option string. 

Thanks

**Comment by orctom** [comment]
Two issues:
1. `webservers` is missing in your plugin section, while you do have it in the profile's properties
2. The plugin is lack of support for `webservers` for standalone WAS, just added it in version `1.1.3.2` (it might take hours to be synced to the public repo)

**Comment by GPCruisr** [comment]
Well, that was a bit embarrassing, included the wrong pom.  Running it with webservers doesn't make a difference.   Looks like I need to use 1.1.3.2 anyway.  I'll download that and give it a shot. 
Thanks
