### ISSUE TITLE
Can it be used for Liberty Profile?

### ISSUE THREAD

**Issue by jitendrachopra** [orctom/was-maven-plugin#3]
I want to deploy my war on remote host. Liberty has it's own plugin but it only allows to deploy war on local box.  Can orctom used for Liberty Profile 8.5.0 version?

Thanks
Jitendra

**Comment by orctom** [comment]
Never tried before, Liberty profile and full profile might be using different mechanism for deployment.
Appreciates if you could provide any input!

**Comment by orctom** [comment]
No, not supported at all.
As the [document](http://www-01.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_about.html) stated, only two ways to deploy to a liberty profile:
- Deploy an application by dropping it into the dropins directory.
- Deploy an application by adding it to the server configuration file.

You should be able to simply scp/rsyc/ftp your package to remote box, placing it into the `dropins` directory by using `maven-antrun-plugin` and/or `exec-maven-plugin`.
