### ISSUE TITLE
wasHome missing or invalid

### ISSUE THREAD

**Issue by skHollywood** [orctom/was-maven-plugin#6]
I am trying to run deploy goal, with the code in Readme.cmd, where wasHome is set. But it gives wasHome missing or invalid. 

I have given value of  was home as

C:\IBM\WebSphere\AppServer_1. 

```
                            <code> Starts Here </code>
                            <configuration>                                
                            <wasHome>${env.WAS_HOME}</wasHome>
                            <applicationName>${project.build.finalName}</applicationName>
                            <host>localhost</host>
                            <server>server1</server>
                            <node>Node01</node>
                            <virtualHost>default_host</virtualHost>

                        </configuration>
                          <code> Ends Here </code>
```

Any Idea?

using below command
mvn -X com.orctom.mojo:was-maven-plugin:1.0.11:deploy

**Comment by orctom** [comment]
${env.WAS_HOME} reads from environment properties (it's Maven built-in mechanism), you have to restart your terminal after you set this property in system environment. 
Or you can try "hard code" the value as 

``` xml
<wasHome>C:\IBM\WebSphere\AppServer_1</wasHome>
```

**Comment by skHollywood** [comment]
This is my configuration. I am using Version. 1.0.11.

<plugins>
          <plugin>
            <groupId>com.orctom.mojo</groupId>
            <artifactId>was-maven-plugin</artifactId>
            <version>1.0.11</version>
            <executions>
              <execution>
                <id>default-cli</id>
                <phase>install</phase>
                <goals>
                  <goal>deploy</goal>

```
            </goals>
              <configuration>
                    <applicationName>Test APP</applicationName>
                    <wasHome1>C:\IBM\WebSphere\AppServer_1</wasHome1>
                    <verbose>true</verbose>
                </configuration>
          </execution>

        </executions>

      </plugin>
    </plugins>
```

Error:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute
goal com.orctom.mojo:was-maven-plugin:1.0.11:deploy (default-cli) on
project mmis-um-deploy: The parameters 'wasHome' for goal
com.orctom.mojo:was-maven-plugin:1.0.11:deploy are missing or invalid
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters
'wasHome' for goal com.orctom.mojo:was-maven-plugin:1.0.11:deploy are
missing or invalid
        at
org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:586)
        at
org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:539)
        at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
        at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:

**Comment by skHollywood** [comment]
Typo Tested both with <wasHome> and <wasHome1>. same error.

 <wasHome>C:\IBM\WebSphere\AppServer_1</wasHome>

Thanks,
Siva

**Comment by skHollywood** [comment]
Dom is coming as below. I dont see <wasHome>.. should it have wasHome?

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <applicationName default-value="${project.build.finalName}"/>
  <deploymentsPropertyFile
default-value="${project.basedir}/was-maven-plugin.properties"/>
  <failOnError default-value="false"/>
  <host default-value="localhost"/>
  <packageFile default-value="${project.artifact.file}"/>
  <pluginArtifacts default-value="${plugin.artifacts}"/>
  <restartAfterDeploy default-value="true"/>
  <project default-value="${project}"/>
</configuration>

Thanks,
Siva

**Comment by orctom** [comment]
Please don't try `<wasHome1>` any more, never said supporting that param.
It's always `<wasHome>`.
And yes you have to have `<wasHome>` in your pom (as an emphasis).

Paste your full pom here if possible, (replace information that you don't want to expose with 'xxx` or something if you need)
