### ISSUE TITLE
Feature:  Ability to map modules to an IHS webserver

### ISSUE THREAD

**Issue by sparty02** [orctom/was-maven-plugin#9]
Use case:

An applicaiton is deployed in a WAS cluster (clusterA), with e.g. 2 servers in the cluster (server1 with port 9081 and server2 with port 9082).  The clustered app is then mapped not only to clusterA, but also to a webserver moduel (e.g. webserver1, an IHS WAS plugin).  This allows the app to be load-balanced over webserver1's port 80, while it seamlessly directs traffic to clusterA (e.g. server1 or server2).

Some pseudo code to accomplish this from [websphere.py](https://github.com/orctom/was-maven-plugin/blob/master/src/main/resources/jython/websphere.py#L103)

``` python
if "" != cluster:
    serverMapping = 'WebSphere:cluster=' + cluster
    if "" != webserver:
        serverMapping += '+WebSphere:server=' + webserver
    options += ['-cluster', cluster, '-MapModulesToServers', [['.*','.*', serverMapping]]]
```

May be of reference: [wsadmin and MapModulesToServers](https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000013778889)

**Comment by sparty02** [comment]
Maybe this could even be generalized to support the ability to map an application to any number of modules (whether that be multiple clusters, multiple servers, and/or a cluster and a web-server).  I think this is subtly different than the multiple deploy target support because, in this case, you are mapping an application to multiple modules on the same deployment manager.

**Comment by orctom** [comment]
If server1 and server2 belongs to clusterA, why don't deploy to clusterA instead?

**Comment by orctom** [comment]
I just got your idea. I didn't realize there're cases that you have to specify the webserver when deploying apps. I just need to select the correct cell and cluster, then the apps are available thru IHS on port 80/443. You might want to switch to this approach.

**Comment by mortench3000** [comment]
We have made the following change to support mapping all webservers:

```
if "" != cluster:
                cell = AdminControl.getCell()
                serverMapping = 'WebSphere:cell=' + cell + ',cluster=' + cluster
                unmanagedNodeNames = AdminTask.listUnmanagedNodes().splitlines()
                for unmanagedNodeName in unmanagedNodeNames:
                    webservers = AdminTask.listServers('[-serverType WEB_SERVER -nodeName ' + unmanagedNodeName + ']').splitlines()
                    for webserver in webservers:
                        webserverName = AdminConfig.showAttribute(webserver, 'name')
                        serverMapping = serverMapping + '+WebSphere:cell=' + cell + ',node=' + unmanagedNodeName + ',server=' + webserverName
                options += ['-cluster', cluster, '-MapModulesToServers', [['.*','.*', serverMapping]]]
```

Also, the server argument should _not_ be part of the install options for cluster installs, since the servers in the cluster propably have different names, eg. server1, server2, server3. However, it is probably just ignored by wsadmin:

```
        options = ['-deployws', '-distributeApp', '-appname', applicationName]
```

Following is a sample options part for a 2-server cluster:

```
options:  ['-deployws', '-distributeApp', '-appname', 'my_service-ear', '-cluster', 'PortalCluster', '-MapModulesToServers', [['.*', '.*', 'WebSphere:cell=mypor1Cell01,cluster=PortalCluster+WebSphere:cell=mypor1Cell01,node=myporihs2UnmanagedNode,server=webserver1+WebSphere:cell=mypor1Cell01,node=myporihs1UnmanagedNode,server=webserver1']], '-MapWebModToVH', [['.*', '.*', 'default_host']]]
```

**Comment by orctom** [comment]
Yes, it make sense that you could have different names for the application servers in the same cluster.
I'm glad that your script meets your requirement, do you have a fully working script? So that I can test if it's compatible with the non-portal version.

**Comment by mortench3000** [comment]
Our script has several changes to support our multi server portal clusters. You can find it over here --> https://github.com/mortench3000/was-maven-plugin/blob/feature/improved-cluster-mgmnt/src/main/resources/jython/websphere.py

**Comment by sparty02** [comment]
:+1:  to @mortench3000 's note about the server option in a cluster deploy.  I had this same confusion as it seemed like the server arg was required, but it didn't really make sense.  I got around this by just randomly picking the first server in the cluster and naming that in the server argument.....not sure if there are "gotchas" with this approach?  Either way, its seems kinda goofy.

**Comment by sparty02** [comment]
> I just got your idea. I didn't realize there're cases that you have to specify the webserver when deploying apps. I just need to select the correct cell and cluster, then the apps are available thru IHS on port 80/443. You might want to switch to this approach.

Not totally sure I follow.  Are you setting some kind of special configuration on the IHS plugin in WAS?  Any chance you have any reference on how to do this?  I've always had to "apply" the application to multiple modules (as described above)....but I'm not a WAS admin expert my any means!

**Comment by orctom** [comment]
I see cases that you will not always bind the app to all web servers, so I made you to put the name of web servers in configurations.

**Comment by orctom** [comment]
@sparty02 'the other approach' is to manually edit the plug-in.xml. It's dirty, but we use a lot, as there're too many url patterns that need to be routed to WAS for an application whose context path is "/".

I added an extra param `webservers` to hold the web server names, comma separated.

**Comment by orctom** [comment]
BTW, it's in `1.1.1`, and I removed an deploy option: `-deployws`, if you do have old soap based webservices, you'll have to add it back in `deployOptions`

**Comment by sparty02** [comment]
@orctom Great!  I'll give it a shot now and let you know....

**Comment by sparty02** [comment]
@orctom Worked great the first try!  Thanks!!

**Comment by orctom** [comment]
Thank you!
